server:
  port: 8501

app:
  id: sc-consul
apollo:
  meta: http://localhost:8080

spring:
  application:
    name: sc-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        ##对应zuul的service-id
        service-name: sc-consul
        health-check-path: /hello
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
logging:
  level:
    com:
      worstezreal: debug


